### ISSUE TITLE
Add ES-Lint rules  

### ISSUE THREAD

**Issue by BMJ-075** [SamyakJoshi/todoApp#9]
i think we should add eslint rules to maintain standard formating and rules across codebase as multiple developers are working on it .

**Comment by SamyakJoshi** [comment]
Please use a popular style guide, for the setup and formatting please add configure prettier that works along with ESLint

**Comment by BMJ-075** [comment]
Alright, I think we should have a session for everyone to decide which style guid and rules we have to follow , and get everyones's suggestions.
 @mayanktamrkar  @Ankit9589599  @singh12345akshay  @AnjaliRathore01  @Vatsal1996 - please povide your inputs as well. 😃

**Comment by BMJ-075** [comment]
@SamyakJoshi  i have added the prettier config as well in the attached pr.
